import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet"/>
      </Head>
      <main className='bg-white h-screen'>
      <button className="btn btn-active">Button</button>
<button className="btn btn-active btn-primary">Button</button>
<button className="btn btn-active btn-secondary">Button</button>
<button className="btn btn-active btn-accent">Button</button>
<button className="btn btn-active btn-ghost">Button</button>
<button className="btn btn-active btn-link">Button</button>
<h1 className='text-5xl text-bold text-black'>heoo</h1>
      </main>
    </>
  )
}
